### PR TITLE
OCPBUGS-6320: Merge `upstream/release-2.8`

### PR DESCRIPTION
**Pull request by rexagod**
Merge `master` with `upstream/release-2.8`.

Refer: https://github.com/rhobs/syncbot/actions/runs/4159105761/jobs/7194854078

### CODE REVIEW

**Comment by simonpasquier** [comment]
I did a diff between your PR and the upstream release-2.8 branch and found one difference in go.mod:

```diff
--- a/go.mod
+++ b/go.mod
@@ -8,7 +8,7 @@ require (
        github.com/oklog/run v1.1.0
        github.com/prometheus/client_golang v1.14.0
        github.com/prometheus/client_model v0.3.0
-       github.com/prometheus/common v0.39.0
+       github.com/prometheus/common v0.37.0
        github.com/prometheus/exporter-toolkit v0.8.2
        github.com/robfig/cron/v3 v3.0.1
        github.com/spf13/cobra v1.6.1

````

**Comment by rexagod** [comment]
Hmm, not sure what caused that discrepancy during the merge. I've updated the version and re-vendored, PTAL. Other than vendors, only the following files differ now.

```
.ci-operator.yaml
.dockerignore
.gitignore
Dockerfile.ocp
OWNERS
```

**Comment by simonpasquier** [comment]
thanks!
/lgtm

**Pull request merged**
