### PR TITLE
Bump to 2.1.1

### PR DESCRIPTION
**Pull request by jan--f**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by jan--f** [comment]
@simonpasquier Seems like the revert of 3e37e8fc253ba2bfc1b9b49a727d9a4c9a487081 causes the test failure. Doe we need to carry that after all or does we need a fix for the test?

**Comment by simonpasquier** [comment]
Ah I think we got a typo: kube-state-metrics runs with `--metric-labels-allowlist=pods=[*],node=[*]` but the latter part should **`nodes=[*]`**

**Comment by jan--f** [comment]
/hold
Postponed till 4.10

**Pull request merged**
