### PR TITLE
feat: Add CSI volume attributes to PV info metric

### PR DESCRIPTION
**Pull request by machadovilaca**
**What this PR does / why we need it**:

This PR adds a new `csi_mounter` and `csi_map_options` for CSI PV in kube_persistentvolume_info metric, to track the mounter used by the volume, and the respective map options configured

**How does this change affect the cardinality of KSM**: *(increases, decreases or does not change cardinality)*

- adds 2 new labels for kube_persistentvolume_info
- but these label values should be static for most of the lifetime of a volume, therefore, since we already have the volume name in the metric, metric total cardinality is not expected to increase 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by simonpasquier** [comment]
:wave: any reason why it can't be submitted upstream first? In general, we don't carry downstream patches. 
cc @rexagod

**Comment by machadovilaca** [comment]
@simonpasquier I opened https://github.com/kubernetes/kube-state-metrics/pull/2133, but the opinion was that these are very CSI drivers specific and would be hard to add them there

**Comment by rexagod** [comment]
Hey @machadovilaca, we don't really merge any "out-of-tree" changes downstream, since that would diverge and open us on unpredictable front given how the areas affecting such a patch will change upstream from one release to another. IMO getting this in upstream would be the way to go, using [`--metric-opt-in-list`](https://github.com/kubernetes/kube-state-metrics/pull/2133#discussion_r1309127793) as you've commented.

**Comment by rexagod** [comment]
ACK, I was under the impression that since adding these labels to the existing metric is getting some pushback, we could possibly introduce a [new metric](https://github.com/kubernetes/kube-state-metrics/pull/2133#discussion_r1309127793) that folks can opt-in to. However, I see that this could open us up for merging one-off metrics for similar use-cases, and thus will need to be evaluated on a case-by-case basis giving priority to the fact that even the hidden metrics are widely beneficial, if not as much as the ones enabled by default. An `--opt-in-labels-list` flag might be an alternative worth exploring as well.

**Pull request closed without merging**
