### PR TITLE
store: add kube_node_role metric

### PR DESCRIPTION
**Pull request by brancz**
Cherry-picks https://github.com/kubernetes/kube-state-metrics/pull/877

@LiliC @paulfantom @s-urbaniak

### CODE REVIEW

**Comment by LiliC** [comment]
/hold

Until we test this.

**Comment by brancz** [comment]
cc @chambridge @fabianofranz @smarterclayton

**Comment by s-urbaniak** [comment]
just in case :)

**Comment by brancz** [comment]
I've tested a cluster-bot cluster with this, and it works as expected.

**Comment by LiliC** [comment]
/hold cancel

🎉 :shipit:

**Pull request merged**
