### PR TITLE
BUG 1859956: Openshift 1.9.7 bump

### PR DESCRIPTION
**Pull request by brancz**
This PR bumps kube-state-metrics to the latest 1.9.x release.

We are in the process of also releasing an alpha version of kube-state-metrics 2.0, we would prefer to use 2.0 as 4.6 will be supported for some time and we would prefer if we didn't have to maintain an non-current major version of kube-state-metrics.

Should we not manage to release a 2.0 alpha release, then we will move ahead with this PR. Opening this already to run tests etc. already so all we would need to do is merge this PR.

(you can already /lgtm though to make things faster should we need to merge this)

/hold

@openshift/openshift-team-monitoring

### CODE REVIEW

**Comment by s-urbaniak** [comment]
nice, thank you!
:crossed_fingers: for the 2.0 release of kube-state-metrics

**Comment by brancz** [comment]
/hold cancel

Unlikely that at this point 2.0-alpha will make it in time.

**Comment by lilic** [comment]
So what was the failure 🤔

**Pull request merged**
