### PR TITLE
Sync with kube-state-metrics 1.9.1 release

### PR DESCRIPTION
**Pull request by LiliC**
Brings in changes from upstream kube-state-metrics

cc @openshift/openshift-team-monitoring

### CODE REVIEW

**Comment by LiliC** [comment]
/retest

something odd happening here 🤷‍♀

**Comment by LiliC** [comment]
/hold

No clue whats up, will figure out on Monday 🤷‍♀

**Comment by s-urbaniak** [comment]
generally lgtm :man_shrugging:

**Comment by s-urbaniak** [comment]
it looks unrelated though:
```
{\"metric\":{\"__name__\":\"ALERTS\",\"alertname\":\"TargetDown\",\"alertstate\":\"firing\",\"job\":\"machine-config-daemon\",\"namespace\":\"openshift-machine-config-operator\",\"service\":\"machine-config-daemon\",\"severity\":\"warning\"},\"value\":[1578671956.161,\"1\"]}
```

**Comment by LiliC** [comment]
Closing as will open PR to bring in 1.9.2 changes instead.

**Pull request closed without merging**
