### PR TITLE
Upstream sync with v1.7

### PR DESCRIPTION
**Pull request by s-urbaniak**
This bumps to upstream v1.7.

/cc @brancz @paulfantom

### CODE REVIEW

**Comment by paulfantom** [comment]
/lgtm cancel

`OWNERS` file is modified and `tariq1890` is added, but he shouldn't be.

**Comment by s-urbaniak** [comment]
@paulfantom good catch, let me remove that entry.

**Comment by s-urbaniak** [comment]
@paulfantom fixed, ptal

**Comment by paulfantom** [comment]
nice!

/lgtm

**Comment by brancz** [comment]
Thanks!

/lgtm
/approve

**Pull request merged**
