### PR TITLE
MON-3548: Merge tag v2.10.1

### PR DESCRIPTION
**Pull request by dgrisonnet**
**What this PR does / why we need it**:

**How does this change affect the cardinality of KSM**: *(increases, decreases or does not change cardinality)*

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by rexagod** [comment]
/lgtm

Only the following files differ, which is expected.
```
.ci-operator.yaml
.dockerignore
.gitignore
Dockerfile.ocp
OWNERS
```

**Comment by rexagod** [comment]
FYI I can see a `rhel-9` update on https://pkgs.devel.redhat.com/cgit/containers/kube-state-metrics/. Should we consider upgrading, in a future PR?

**Comment by dgrisonnet** [comment]
I tried pulling the updated manifests in CMO by revendoring kube-prometheus but for some reasons, make update + generate didn't fetch the 2.10.1 ksm manifests. If any of you have some time to look into it, that would very appreciated

**Comment by simonpasquier** [comment]
@rexagod are you talking about https://github.com/openshift/kube-state-metrics/pull/105? It seems unrelated to this PR.

@dgrisonnet CMO is pinned to the main branch of kube-prometheus which is itself pinned to the main branch of kube-state-metrics. Why do you need the updated jsonnet from ksm?

**Review by simonpasquier — COMMENTED** [review]
We need a JIRA ticket to merge this. Looking at the changelog, I don't see a bug that we could "leverage" but maybe I missed something. It's also ok to create a ticket in the MON project and link it here.

**Pull request merged**
